version: '3.8'

services:
  postgres:
    image: postgres:14-alpine
    container_name: swiftroute_postgres
    environment:
      POSTGRES_USER: swiftroute_user
      POSTGRES_PASSWORD: dev_password
      POSTGRES_DB: swiftroute_dev
    ports:
      - "5433:5432"  # Changed from 5432:5432
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:7-alpine
    container_name: swiftroute_redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

volumes:
  postgres_data:
  redis_data:
